apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-node-name
  labels:
    app: nginx-node-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-node-name
  template:
    metadata:
      labels:
        app: nginx-node-name
    spec:
      containers:
        - imagePullPolicy: Always
          name: container-0
          args:
            - sh
            - '-c'
            - >-
              nginx  && while true; do curl -m 1 -s http://node-name-svc:8080 >> /dev/null; sleep 3; done
          image: nginxinc/nginx-unprivileged:alpine 
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
