apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-name
  labels:
    name: nginx-node-name
  namespace: default
spec:
  containers:
    - imagePullPolicy: Always
      name: container-0
      args:
        - sh
        - '-c'
        - >-
          /usr/bin/env | grep NODE_NAME= > /usr/share/nginx/html/index.html &&
          nginx >> /dev/null && while true; do curl -s node-name-svc; sleep 3; done
      image: nginx:alpine
      ports:
        - name: http
          protocol: TCP
          containerPort: 80
      env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName