apiVersion: v1
kind: Service
metadata:
  name: node-name-svc
  annotations:
    # Enable the global service
    io.cilium/global-service: "true"
    # Possible values: local, remote, none
    io.cilium/service-affinity: "remote"
spec:
  selector:
    app: nginx-node-name
  ports:
    - port: 8080
      targetPort: 8080
      name: http
